site_name: DjNRO
repo_url: https://github.com/grnet/djnro/
docs_dir: docs
site_author: Stavros Kroustouris
theme: readthedocs
pages:
    - 'Introduction': 'index.md'
    - 'Installation':
        - 'Requirements': 'installation/requirements.md'
        - 'Installing DjNRO': 'installation/install.md'
        - 'Upgrading from 0.8': 'installation/upgrading-from-0.8.md'
